apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  metrics:
    enabled: true
    recordErrorCodes: true
    http:
      increasedCardinality: false
      pathMatching:
        - //v1.0/actors/WeatherActor/{ActorID}/method/GetWeatherAsync

  tracing:
    samplingRate: "0"
    zipkin:
      endpointAddress: http://localhost:9411/api/v2/spans
